const MONGO_URL = "";
const COLLECTION_NAME = "users";
const COLLECTION_STOPS = "stops";
const COLLECTION_LIGNE = "lignes";

busStops482 = [
  "Jeanne D'Arc",
  "Lycée Brassens",
  "Weddingen",
  "Raoul Delattre",
  "Edf",
  "Ecoles",
  "Place Paul Bert",
  "La Fresnaie",
  "Parc En Seine",
  "Rue de la Paix",
  "Gare de Villeneuve-Le-Roi P. Painlevé",
  "Gare de Villeneuve-Le-Roi",
  "Marché",
  "Place Amédée Soupault",
  "Place Molière",
  "Henri Dunant",
  "Paul Painlevé / Place Gounot",
  "Cimetières",
  "Gaston Viens / Fer À Cheval",
  "J.-J. Rousseau",
  "Mairie",
  "Parc Méliès",
  "Cimetière Paysager",
  "Cité Jardins",
  "Pont de Rungis",
  "Hauts Flouviers",
  "Pont D'Espagne",
  "Belle Epine Nord",
  "Belle Epine Sud",
].toList();
busStops480 = [
  "Gare de Villeneuve-Saint-Georges",
  "Raoul Delattre",
  "Weddingen",
  "Lycée Brassens",
  "Brossolette",
  "Gare D'Ablon",
  "Sacré Coeur",
  "Tamaris Le Parc",
  "Château D'Ablon",
  "Za Les Guyards",
  "Rue du Musée",
  "Dgac",
  "Parc Central",
  "Maison de L'Environnement",
  "Porte de L'Essonne",
  "Aéroport Orly 4",
  "Orly 1-2-3",
].toList();
busStops483 = [
  "Gare de Villeneuve-Saint-Georges",
  "Raoul Delattre",
  "Weddingen",
  "Lycée Brassens",
  "Brossolette",
  "Gare D'Ablon",
  "Reine Astrid",
  "Place de la République",
  "Place Amédée Soupault",
  "Paul Painlevé / Place Gounot",
  "Place Colonel A. Beltrame",
  "Gare D'Orly-Ville",
  "J.-J. Rousseau",
  "Gaston Viens / Fer À Cheval",
  "La Victoire",
  "Paul Lafargue",
  "La Source",
  "Noyer Grenot",
  "Jean Jaurès",
  "Les Tilleuls",
  "Spinoza",
  "Lycée / de Lattre de Tassigny",
  "Guy Môquet",
  "Général Leclerc",
  "Rouget de Lisle",
  "Gare de Choisy-Le-Roi",
].toList();
busStops282 = [
  "E. Levassor",
  "Marmontel",
  "Institut Grignon",
  "Stade A. Mimoun",
  "Pavé Grignon",
  "Cité Des Vergers",
  "Guy Môquet",
  "Général Leclerc",
  "Rouget de Lisle",
  "Gare de Choisy-Le-Roi",
  "8 Mai 1945",
  "Docteur Roux",
  "Jules Guesde",
  "Passerelle",
  "Rue Des Fusillés",
  "Rue Tortue",
  "Eugène Hénaff",
  "Charles Heller",
  "Pont de Vitry",
  "Centre Commercial Pont de Vitry",
].toList();
busStopsLicorne = [
  "Pierre Curie",
  "Rue Foch",
  "Les Pierrières",
  "Ernest Renan",
  "Place Amédée Soupault",
  "Victor Hugo",
  "Jeanne D'Arc",
  "Lycée Brassens",
  "Weddingen",
  "Raoul Delattre",
  "Edf",
  "Ecoles",
  "Place Paul Bert",
  "La Fresnaie",
  "Parc En Seine",
  "Rue de la Paix",
  "Gare de Villeneuve-Le-Roi",
  "Général de Gaulle",
  "Poincaré",
  "Marché",
  "Louis Jarrige",
  "Abbé Grégoire",
  "Nikos Belloyanis",
  "Gallieni",
  "Ecole Paul Painlevé",
  "Place Colonel A. Beltrame",
  "Guillaume du Vair",
  "Foyer Jean Rostand",
].toList();
t9Arr = [
  "",
  "Gaston Viens",
  "Les Saules",
  "Christophe Colomb",
  "Four - Peary",
  "Carle - Darthé",
  "Rouget de Lisle",
  "Verdun - Hoche",
  "Trois Communes",
  "Watteau - Rondenay",
  "Constant Coquelin",
  "Camille Groult",
  "Mairie de Vitry-Sur-Seine",
  "Musée Mac Val",
  "Beethoven - Concorde",
  "Germaine Tailleferre",
  "La Briqueterie",
  "Cimetière Parisien D'Ivry",
  "Châteaudun - Barbès",
  "Porte de Choisy",
].toList();
